version: '3.8'

services:
  couchbase:
    image: couchbase:community-7.1.3
    container_name: couchbase_container
    ports:
      - "8091:8091" # Админка
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var # Хранилище данных
    environment:
      - COUCHBASE_ADMIN_USERNAME=admin
      - COUCHBASE_ADMIN_PASSWORD=password
      - COUCHBASE_MEMORY_QUOTA=256 # Память в MB

volumes:
  couchbase_data:
    driver: local
