version: '3.8'

services:
  couchbase:
    image: couchbase:community
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094" # Админ-панель и сервисы
      - "11210:11210"         # Протокол передачи данных
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: admin
      COUCHBASE_ADMINISTRATOR_PASSWORD: password
    volumes:
      - couchbase-data:/opt/couchbase/var

volumes:
  couchbase-data:
